<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="BitMiracle.LibTiff.NET" Version="2.4.660" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="itext" Version="9.3.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.3.0" />
    <PackageReference Include="itext7.bouncy-castle-fips-adapter" Version="9.3.0" />
    <PackageReference Include="MailKit" Version="4.13.0" />
    <PackageReference Include="MarkdownStructureChunker" Version="1.0.4" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.65.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.65.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" Version="1.65.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PdfPig" Version="0.1.11" />
    <PackageReference Include="SemanticChunker.NET" Version="1.0.1" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" Version="2.1.6" />
    <PackageReference Include="SixLabors.ImageSharp.Web" Version="3.2.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.0" />
    <PackageReference Include="Syncfusion.EJ2.PdfViewer.AspNet.Core" Version="30.1.41" />
    <PackageReference Include="Syncfusion.EJ2.SpellChecker.AspNet.Core" Version="30.1.41" />
    <PackageReference Include="Syncfusion.EJ2.Spreadsheet.AspNet.Core" Version="30.1.41" />
    <PackageReference Include="Syncfusion.EJ2.WordEditor.AspNet.Core" Version="30.1.41" />
    <PackageReference Include="Syncfusion.Licensing" Version="30.1.41" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.9" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="Tesseract" Version="5.2.0" />
    <PackageReference Include="Tesseract.Drawing" Version="5.2.0" />
    <PackageReference Include="Tesseract.Net.Sdk" Version="4.6.411" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Api.Extensions\Api.Extensions.csproj" />
    <ProjectReference Include="..\..\Api.Language\Api.Language.csproj" />
    <ProjectReference Include="..\..\DataAccess\Api.Repository\Api.Repository.csproj" />
  </ItemGroup>

</Project>
