// <auto-generated />
using System;
using Api.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Api.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.DataAccess.Models.Dms.ApprovalActivities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalActivity")
                        .HasColumnType("integer");

                    b.Property<string>("ApprovalActivityName")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("ApprovalID")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("NextStep")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("varchar(2000)");

                    b.Property<int?>("RelatedDocumentID")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalID");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("RelatedDocumentID");

                    b.ToTable("TblApprovalActivities");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.ApprovalFlows", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovalID")
                        .HasColumnType("integer");

                    b.Property<int>("ApproverUserID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFinalStep")
                        .HasColumnType("boolean");

                    b.Property<int>("Step")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalID");

                    b.HasIndex("ApproverUserID");

                    b.ToTable("TblApprovalFlows");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Approvals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentApproverUserID")
                        .HasColumnType("integer");

                    b.Property<int?>("CurrentStep")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastActivityDate")
                        .HasColumnType("timestamp");

                    b.Property<string>("LastRemark")
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("MaxStep")
                        .HasColumnType("integer");

                    b.Property<int?>("NextApproverUserID")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("CurrentApproverUserID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("NextApproverUserID");

                    b.ToTable("TblApproval");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.AttributeCollections", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AttributeElementCollection")
                        .HasColumnType("json");

                    b.Property<string>("CollectionDescription")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CollectionName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblAttributeCollections");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Attributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeElement")
                        .HasColumnType("json");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AttributeType")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblAttributes");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryDesc")
                        .HasColumnType("text");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNeedApproval")
                        .HasColumnType("boolean");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Owner");

                    b.HasIndex("ParentId");

                    b.ToTable("TblCategories");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.CategoriesFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("TblCategoriesFavorite");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.CategoriesShared", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("GroupID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsView")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("GroupID");

                    b.HasIndex("UserID");

                    b.ToTable("TblCategoriesShared");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentAttributes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeValues")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.ToTable("TblDocumentAttributes");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblDocumentFavorite");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributtes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DocumentFileContent")
                        .HasColumnType("text");

                    b.Property<string>("DocumentFileName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("DocumentFilePath")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DocumentFileSize")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<string>("DocumentSummary")
                        .HasColumnType("text");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMainDocumentFile")
                        .HasColumnType("boolean");

                    b.Property<string>("NewDocumentFileName")
                        .HasColumnType("varchar(150)");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "DocumentFileContent" });

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TblDocumentFiles");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentItemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("ItemUser")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.HasIndex("ItemUser");

                    b.ToTable("TblDocumentItemList");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ActionLogDocument")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LogAuditTrailID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.HasIndex("LogAuditTrailID");

                    b.ToTable("TblDocumentLogs");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentRelated", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RelatedDocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RelatedDocumentID");

                    b.ToTable("TblDocumentRelated");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentReminders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ReminderDateTime")
                        .HasColumnType("timestamp");

                    b.Property<string>("ReminderDesc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblDocumentReminders");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentShared", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.ToTable("TblDocumentShared");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentSharedPrivillege", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DocumentSharedID")
                        .HasColumnType("integer");

                    b.Property<int?>("GroupID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEdit")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsView")
                        .HasColumnType("boolean");

                    b.Property<string>("ShareType")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("UserID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentSharedID");

                    b.HasIndex("GroupID");

                    b.HasIndex("UserID");

                    b.ToTable("TblDocumentSharedPrivillege");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Documents", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DocumentDesc")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DocumentTitle")
                        .IsRequired()
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp");

                    b.Property<int?>("FileSize")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Owner")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReminderDateTime")
                        .HasColumnType("timestamp");

                    b.Property<short?>("ReminderDays")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<int?>("WatermarkID")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.HasIndex("Owner");

                    b.HasIndex("WatermarkID");

                    b.ToTable("TblDocuments");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Notifications", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("DocumentID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("NotifAction")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NotifContent")
                        .HasColumnType("text");

                    b.Property<string>("NotifDescription")
                        .HasColumnType("varchar(255)");

                    b.Property<short>("NotificationType")
                        .HasColumnType("smallint");

                    b.Property<int>("TargetActor")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocumentID");

                    b.ToTable("TblNotification");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Watermarks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("TblWatermarks");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Address")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ParentCompanyId")
                        .HasColumnType("varchar(15)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("CompanyId");

                    b.ToTable("TblMsCompany");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GroupDescription")
                        .HasColumnType("varchar(500)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("GroupId");

                    b.ToTable("TblMsGroup");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("En")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Id")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(10)");

                    b.HasKey("Code");

                    b.ToTable("TblMsLanguage");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Menu", b =>
                {
                    b.Property<string>("MenuId")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("ParentMenuId")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("varchar(200)");

                    b.HasKey("MenuId");

                    b.ToTable("TblMsMenu");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.ResetPasswordUserVerificationCode", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("TblMsUserResetPasswordVerificationCodes");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("RoleId");

                    b.ToTable("TblMsRole");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.RoleMatrix", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("MenuId")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInsert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("TblMsRoleMatrix");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsADUser")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsLogin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(18)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPassword")
                        .HasColumnType("text");

                    b.Property<int?>("UserStatus")
                        .HasColumnType("integer");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TblMsUser");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserCompany", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(15)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "CompanyId");

                    b.HasIndex("CompanyId");

                    b.ToTable("TblMsUserCompany");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserGroup", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("TblMsUserGroups");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserMatrix", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("MenuId")
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInsert")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("TblMsUserMatrix");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserMedia", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("PhotoImage")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoName")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("TblMsUserMedia");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("TblMsUserRoles");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.ApplicationLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(39)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Parameter")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("varchar(30)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TblLogApplication");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid?>("TransactionLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InsertedBy");

                    b.HasIndex("TransactionLogId")
                        .IsUnique();

                    b.ToTable("TblLogAuditTrail");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.Email", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cc")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<int>("SentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblTrEmail");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.HistoryAuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("After")
                        .HasColumnType("text");

                    b.Property<string>("Before")
                        .HasColumnType("text");

                    b.Property<string>("Command")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("TableName")
                        .HasColumnType("varchar(50)");

                    b.Property<Guid>("TransactionLogId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("TblHistoryLogAuditTrail");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.HistoryEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cc")
                        .HasColumnType("text");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<short>("SentStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusMessage")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TblHistoryTrEmail");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.HistoryTransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(39)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TblHistoryLogTransaction");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.LoginActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ActorUserId")
                        .HasColumnType("integer");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(39)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp");

                    b.Property<string>("UserAction")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TblLogActivityLogin");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.MigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionStringHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MigrationJobs", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.TransactionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Action")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("IPAddress")
                        .HasColumnType("varchar(39)");

                    b.Property<DateTime>("InsertedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("InsertedBy")
                        .HasColumnType("integer");

                    b.Property<string>("Parameter")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("TblLogTransaction");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.ApprovalActivities", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Approvals", "Approvals")
                        .WithMany("ApprovalActivities")
                        .HasForeignKey("ApprovalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "InsertedUser")
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "RelatedDocument")
                        .WithMany()
                        .HasForeignKey("RelatedDocumentID");

                    b.Navigation("Approvals");

                    b.Navigation("InsertedUser");

                    b.Navigation("RelatedDocument");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.ApprovalFlows", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Approvals", "Approvals")
                        .WithMany("ApprovalFlows")
                        .HasForeignKey("ApprovalID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany()
                        .HasForeignKey("ApproverUserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approvals");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Approvals", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Categories", "Categories")
                        .WithMany("Approvals")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Api.DataAccess.Models.Masters.User", "CurrentApproverUser")
                        .WithMany()
                        .HasForeignKey("CurrentApproverUserID");

                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Documents")
                        .WithMany()
                        .HasForeignKey("DocumentID");

                    b.HasOne("Api.DataAccess.Models.Masters.User", "InsertedUser")
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "NextApproverUser")
                        .WithMany()
                        .HasForeignKey("NextApproverUserID");

                    b.Navigation("Categories");

                    b.Navigation("CurrentApproverUser");

                    b.Navigation("Documents");

                    b.Navigation("InsertedUser");

                    b.Navigation("NextApproverUser");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Categories", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.User", "OwnerInfo")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Dms.Categories", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("OwnerInfo");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.CategoriesFavorite", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Categories", "Categories")
                        .WithMany("CategoriesFavorite")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.CategoriesShared", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Categories", "Category")
                        .WithMany("CategoriesShareds")
                        .HasForeignKey("CategoryID");

                    b.HasOne("Api.DataAccess.Models.Masters.Group", "GroupInfo")
                        .WithMany()
                        .HasForeignKey("GroupID");

                    b.HasOne("Api.DataAccess.Models.Masters.User", "user")
                        .WithMany("CategoriesShared")
                        .HasForeignKey("UserID");

                    b.Navigation("Category");

                    b.Navigation("GroupInfo");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentAttributes", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Documents")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentFiles", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Documents")
                        .WithMany("DocumentFiles")
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "InsertedByUser")
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("Documents");

                    b.Navigation("InsertedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentItemList", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany()
                        .HasForeignKey("ItemUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentLog", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Documents")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Systems.AuditTrail", "AuditTrls")
                        .WithMany()
                        .HasForeignKey("LogAuditTrailID");

                    b.Navigation("AuditTrls");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentRelated", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Documents")
                        .WithMany("RelatedDocuments")
                        .HasForeignKey("RelatedDocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentShared", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentSharedPrivillege", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.DocumentShared", "DocumentShared")
                        .WithMany("DocumentSharePrivs")
                        .HasForeignKey("DocumentSharedID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.Group", "GroupInfo")
                        .WithMany()
                        .HasForeignKey("GroupID");

                    b.HasOne("Api.DataAccess.Models.Masters.User", "UsersInfo")
                        .WithMany()
                        .HasForeignKey("UserID");

                    b.Navigation("DocumentShared");

                    b.Navigation("GroupInfo");

                    b.Navigation("UsersInfo");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Documents", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Categories", "Categories")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "OwnerInfo")
                        .WithMany()
                        .HasForeignKey("Owner")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Dms.Watermarks", "Watermark")
                        .WithMany()
                        .HasForeignKey("WatermarkID");

                    b.Navigation("Categories");

                    b.Navigation("OwnerInfo");

                    b.Navigation("Watermark");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Notifications", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Dms.Documents", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentID");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Watermarks", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.User", "InsertedUser")
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "UpdatedUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("InsertedUser");

                    b.Navigation("UpdatedUser");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.RoleMatrix", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Menu", "Menu")
                        .WithMany("RoleMatrices")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.Role", "Role")
                        .WithMany("RoleMatrices")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.User", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserCompany", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany("UserCompanies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserGroup", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Group", "Group")
                        .WithMany("UserGroup")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany("UserGroup")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserMatrix", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Menu", "Menu")
                        .WithMany("UserMatrices")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany("UserMatrices")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserMedia", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithOne("UserMedia")
                        .HasForeignKey("Api.DataAccess.Models.Masters.UserMedia", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.UserRole", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Masters.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.AuditTrail", b =>
                {
                    b.HasOne("Api.DataAccess.Models.Masters.User", "InsertedByUser")
                        .WithMany()
                        .HasForeignKey("InsertedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.DataAccess.Models.Systems.TransactionLog", "TransactionLog")
                        .WithOne("Audit")
                        .HasForeignKey("Api.DataAccess.Models.Systems.AuditTrail", "TransactionLogId");

                    b.Navigation("InsertedByUser");

                    b.Navigation("TransactionLog");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Approvals", b =>
                {
                    b.Navigation("ApprovalActivities");

                    b.Navigation("ApprovalFlows");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Categories", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("CategoriesFavorite");

                    b.Navigation("CategoriesShareds");

                    b.Navigation("ChildCategories");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.DocumentShared", b =>
                {
                    b.Navigation("DocumentSharePrivs");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Dms.Documents", b =>
                {
                    b.Navigation("DocumentFiles");

                    b.Navigation("RelatedDocuments");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Group", b =>
                {
                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Menu", b =>
                {
                    b.Navigation("RoleMatrices");

                    b.Navigation("UserMatrices");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.Role", b =>
                {
                    b.Navigation("RoleMatrices");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Masters.User", b =>
                {
                    b.Navigation("CategoriesShared");

                    b.Navigation("UserCompanies");

                    b.Navigation("UserGroup");

                    b.Navigation("UserMatrices");

                    b.Navigation("UserMedia");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Api.DataAccess.Models.Systems.TransactionLog", b =>
                {
                    b.Navigation("Audit");
                });
#pragma warning restore 612, 618
        }
    }
}
