<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Masters\**" />
    <EmbeddedResource Remove="Masters\**" />
    <None Remove="Masters\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Masters\CompanyRepository.cs" />
    <Compile Include="Masters\LanguageRepository.cs" />
    <Compile Include="Masters\MenuRepository.cs" />
    <Compile Include="Masters\RoleMatrixRepository.cs" />
    <Compile Include="Masters\GroupRepository.cs" />
    <Compile Include="Masters\RoleRepository.cs" />
    <Compile Include="Masters\UserCompanyRepository.cs" />
    <Compile Include="Masters\UserMatrixRepository.cs" />
    <Compile Include="Masters\UserRepository.cs" />
    <Compile Include="Masters\UserGroupRepository.cs" />
    <Compile Include="Masters\UserRoleRepository.cs" />
    <Compile Include="Masters\DocumentTypeRepository.cs" />
    <Compile Include="Masters\IDocumentTypeRepository.cs" />
    <Compile Include="Masters\DocumentTypeAttributesRepository.cs" />
    <Compile Include="Masters\IDocumentTypeAttributesRepository.cs" />
    <Compile Include="Masters\AttributeSynonymsRepository.cs" />
    <Compile Include="Masters\IAttributeSynonymsRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="EFCore.BulkExtensions" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="10.7.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <!-- <PackageReference Include="System.Formats.Asn1" Version="10.0.0" /> -->
    <!-- <PackageReference Include="System.Net.Http" Version="4.3.4" /> -->
    <!-- <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" /> -->
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\Api.Domain\Api.Domain.csproj" />
    <ProjectReference Include="..\..\Api.Extensions\Api.Extensions.csproj" />
    <ProjectReference Include="..\..\DataAccess\Api.DataAccess\Api.DataAccess.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Transactions\" />
  </ItemGroup>

</Project>
